AVAIL_RUNTIMES = ['nodejs4.3', 'nodejs6.10', 'java8', 'python2.7', 'python3.6', 'dotnetcore1.0', 'nodejs4.3-edge']
AVAIL_ACTIONS = ['create', 'update-code', 'update-config','delete', 'publish', 'create-alias', 'delete-alias', 'update-alias']
REGIONS = ['eu-west-1', 'us-west-1', 'us-west-2', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2','ap-northeast-1', 'sa-east-1', 'cn-north-1', 'eu-central-1']
ACL_ANSWERS = ['private', 'public-read', 'public-read-write', 'authenticated-read']
PRINCIPALS = ['s3', 'sqs', 'sns', 'cloudwatch']
